#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t tripndroid"

$L "____ _   _ ____ _  _ ____ ____ ____ _  _ _  _ ____ ___";
$L "|     \\_/  |__| |\\ | |  | | __ |___ |\\ | |\\/| |  | |  \\";
$L "|___   |   |  | | \\| |__| |__] |___ | \\| |  | |__| |__/";
$L "TripNDroid Mobile Engineering";
